version: '3.3'
services:
  web:
    image: nginx:latest
    #restart: always
    container_name: nginx
    ports:
     - "8080:80"
    volumes:
      - "./:/var/www/html"
      - "./site.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
    -  php
  php:
    image: php:latest
    build:
        context: .
        dockerfile: Dockerfile
    #restart: always
    container_name: php
    volumes:
      - "./:/var/www/html"
      - "./php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf"
      - "./php-cust.ini:/usr/local/etc/php/php.ini"
    depends_on:
      - db
  db:
    image: bitnami/mariadb
    #restart: always
    container_name: mysql
    ports:
        - "3306:3306"
    expose:
        - "3306"
    volumes:
        - 'mysql:/var/lib/mysql'
    environment:
        ALLOW_EMPTY_PASSWORD: 'yes'
        MARIADB_DATABASE: 'bkpsdma_db'
volumes:
    mysql:
